services:
  postgres-server:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: local
    ports:
      - "15432:5432"
    volumes:
      - postgres-server-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin-server:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "18082:80"
    depends_on:
      - postgres-server
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:latest
    ports:
      - "15678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres-server
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=local
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=12345
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
    volumes:
      - ./n8n_data:/home/node/.n8n
    depends_on:
      - postgres-server
    restart: unless-stopped

volumes:
  postgres-server-data:
